name: geofencing
description: A geofencing plugin for Flutter applications.
version: 0.2.0
homepage: https://github.com/flutter/plugins

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.geofencing
        pluginClass: GeofencingPlugin
      ios:
        pluginClass: GeofencingPlugin